project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - R_code_Intro_NARCH_2026_06.zip

website:
  title: "Data Wrangling & Summarizing in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



